title: Anna Carla ARAUJO   # Add a space after the period

logo: ac.png # Use a relative path to logo image 

description: Manufacturing and Smart Machining # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin 

email: araujo (at) insa-toulouse.fr # Allow visitors to contact you
